[package]
name = "foundry-test"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { git = "https://github.com/Lagrange-Labs/ethers-rs", default-features = false, features = ["rustls"], branch = "get-proof-0x" }
tokio = { version = "1.34", features = ["macros", "rt-multi-thread"] }
