[profile.default]
src = "test-contracts/src"
out = "test-contracts/out"
broadcast = "test-contracts/broadcast"
script = "test-contracts/script"
libs = ["test-contracts/lib"]
optimizer = true
optimizer_runs = 200
solc-version = "0.8.24"
evm_version = "cancun"
verbosity = 4

[fmt]
line_length = 80

[rpc_endpoints]
local = "http://0.0.0.0:8545"
