on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches:
      - main

jobs:
  test:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo test
        run: cargo test --all --release -- --test-threads 16
